name: padp-vla
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - numpy<2.0          # robomimic 0.3 与 numpy 2.x 不兼容
  - h5py
  - hdf5
  - pytest
  - tqdm
  - rich
  - pytorch::pytorch=2.4.1
  - pytorch::pytorch-cuda=12.4
  - pip:
      - einops
      - hydra-core
      - omegaconf
      - pyyaml
      - wandb
      - zarr==2.18.2
      - numcodecs
      - imagecodecs
      - diffusers==0.30.0
      - matplotlib
      - pyzmq
      - msgpack-numpy
      - gym==0.21.0
      - robomimic==0.3.0
      - mujoco==2.3.7
      - mjrl
